version: 0.0
os: windows
files:
 - source: .
   destination: C:\temp\apps\magicbot
hooks:
  AfterInstall:
   - location: scripts\build.ps1
     timeout: 60
  ApplicationStart:
   - location: scripts\start_app.ps1
     timeout: 10